@ECHO OFF
ECHO Starting C3 StarMapFX...

IF EXIST jre\bin\java.exe (GOTO INCLUDEDJAVARUNTIME) ELSE (GOTO INSTALLEDJAVARUNTIME)

:INCLUDEDJAVARUNTIME
java.exe -jar C3-StarMapFX.jar
GOTO END

:INSTALLEDJAVARUNTIME
jre\bin\java.exe -jar C3-StarMapFX.jar
GOTO END

:END
PAUSE
